app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
]

character/urls.py
from django.urls import path
from . import views

app_name = "character"
urlpatterns = [
    path("", views.index, name="index"),
    path("create", views.create, name="create"),
    path("<int:character_id>", views.detail, name="detail"),
]

characterbuilder/urls.py
from django.contrib import admin
from django.urls import include, path
from character import views as characterViews

urlpatterns = [
    path("", characterViews.index), # zmienić na party
    path("character/", include("character.urls")),
    path("user/", include("user.urls")),
    path("admin/", admin.site.urls),
]

user/urls.py
from django.urls import path
from . import views

app_name = "user"
urlpatterns = [
    path("", views.login_view, name="blank"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.register_view, name="register")
]

character/models.py
# TODO: Znaleźć jak robi się Join w django, żeby połączyć parę modeli w jedną listę, np. Party z PartyCharacter i Character

from django.db import models
from django.contrib.auth.models import User

class Skill(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name

class Profession(models.Model):
    name = models.CharField(max_length=50)
    short = models.CharField(max_length=10)
    def __str__(self):
        return self.name

class Party(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    gold = models.IntegerField()
    def getCharacters(self):
        # TODO: Character.objects.all()
        # then filter, where Character.party == self
        # https://docs.djangoproject.com/en/2.2/ref/models/querysets/#select-related
        return None

class Character(models.Model):
    name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    race = models.CharField(max_length=50)
    exp = models.IntegerField(default=0)
    skill = models.ForeignKey(Skill, on_delete=models.CASCADE)
    profession = models.ForeignKey(Profession, on_delete=models.CASCADE)
    party = models.ForeignKey(Party, on_delete=models.CASCADE)
    def getName(self):
        return self.name + " " + self.last_name
    def getLevel(self):
        # TODO: Tutaj znaleźć funkcję w stylu Math.floor, żeby zwróciła liczbę całkowitą, zamiast 1,3 level
        # return floor(exp / 1000)
        return
    def __str__(self):
        return getName(self)

class Quest(models.Model):
    name = models.CharField(max_length=50)
    minLevel = models.IntegerField(default=1)
    exp = models.IntegerField(default=200)
    gold = models.IntegerField(default=200)
    time = models.IntegerField(default=10000)
    def getByLevel(self, level):
        # pobierz wszystkie i odfiltruj <= level
        return

class CharacterQuest(models.Model):
    QUEST_STATUS = [
        ('completed', 'Completed'),
        ('pending', 'Pending')
    ]
    character = models.ForeignKey(Character, on_delete=models.CASCADE)
    quest = models.ForeignKey(Quest, on_delete=models.CASCADE)
    timeStart = models.DateField(auto_now=False, auto_now_add=True)
    status = models.CharField(max_length=10, choices=QUEST_STATUS, default='pending')
    def complete(self):
        currentTime = time.time()
        # if (currentTime > (timeStart + quest.time)) {
        #    super().save(update_fields=["status"])
        #}
        return

user/models.py
from django.db import models

# Create your models here.

character/views.py
from django import forms
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from .models import Character

def index(request):
    if request.user.is_authenticated == False:
        return redirect("user:login")
    characters = Character.objects.all()
    return render(request, "character/index.html", {"list": characters, "user": request.user})

def detail(request, character_id):
    if request.user.is_authenticated == False:
        return redirect("user:login")
    character = get_object_or_404(Character, pk=character_id)
    return render(request, "character/details.html", {"character": character})

class CharacterForm(forms.Form):
    name = forms.CharField(label="Imię", max_length=100)
    last_name = forms.CharField(label="Nazwisko", max_length=100)
    race = forms.CharField(label="Rasa", max_length=100)
    characterClass = forms.CharField(label="Klasa", max_length=100)
    level = forms.CharField(label="Poziom", max_length=100)

def create(request):
    if request.user.is_authenticated == False:
        return redirect("user:login")

    if request.method == 'POST':
        form = CharacterForm(request.POST)
        if form.is_valid():
            # TODO: dodać do formularza postaci pole wyboru skillów, profesji itd. i zapisać poniżej w polach
            character = Character.objects.create(
                name = form.cleaned_data["name"],
                last_name = form.cleaned_data["last_name"],
                race = form.cleaned_data["race"],
                exp = 0,
            )
            return redirect('character:detail', character.id)
        return render(request, 'character/form.html', {"error_message": "Form is invalid"})
    else:
        form = CharacterForm()
        return render(request, 'character/form.html', {"form": form})

user/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

def login_view(request):
    if request.method == 'POST':
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("character:index")
        else:
            return render(request, "user/login.html", {"error_message": "Niepoprawne dane logowania"})
    else:
        return render(request, "user/login.html")

def logout_view(request):
    logout(request)
    return render(request, "user/logout.html")

def register_view(request):
    if request.method == 'POST':
        username = request.POST["username"]
        password = request.POST["password"]
        passwordRepeat = request.POST["passwordRepeat"]
        if password != passwordRepeat:
            return render(request, "user/register.html", {"error_message": "Hasła różnią się od siebie"})
        user = User.objects.create_user(username, None, password)
        if user is not None:
            return redirect("character:index")
        else:
            return render(request, "user/login.html", {"error_message": "Coś poszło nie tak"})
    else :
        return render(request, "user/register.html")

character/templates/character/delete.html
#Szablon dla widoku potwierdzenia usunięcia postaci:
{% extends "base.html" %}

{% block content %}
<h2>Czy na pewno chcesz usunąć postać "{{ character.name }}"?</h2>
<form method="post">
    {% csrf_token %}
    <button type="submit">Tak, usuń</button>
</form>
<a href="{% url 'character_detail' character.id %}">Anuluj</a>
{% endblock %}

character/templates/character/details.html
{% extends "base.html" %}

{% block title %}Character - {{character.name}} {{character.last_name}}{% endblock %}

{% block content %}
<div class="px-4 py-5 my-5 text-center">
    <h1 class="display-5 fw-bold text-body-emphasis">{{character.name}} {{character.last_name}}</h1>
    <a href="{% url 'character:index'  %}" class="btn btn-sm btn-light">Wróć</a>
</div>
{% endblock %}

character/templates/character/form.html
{% extends "base.html" %}

{% block title %}Utwórz postać{% endblock %}

{% block content %}
<div class="container d-flex justify-content-center">
  <main class="w-25 text-center" style="margin-top: 10rem">
    <form action="{% url 'character:create' %}" method="post">
      {% csrf_token %}
      {{ form.as_div }}
      <button type="submit" class="btn btn-dark">Utwórz</button>
    </form>
  </main>
</div>
{% endblock %}

character/templates/character/form_div.html
<div class="mb-3"></div>

character/templates/character/index.html
{% extends "base.html" %}

{% block title %}Character List{% endblock %}

{% block content %}
<div class="px-4 py-5 my-5 text-center">
    <h1 class="display-5 fw-bold text-body-emphasis">Lista postaci</h1>
    <p>Cześć, {{user.username}}</p>
    <a href="{% url 'character:create' %}" class="btn btn-sm btn-dark">Dodaj nową</a>
    <a href="{% url 'user:logout' %}" class="btn btn-sm btn-light">Wyloguj</a>
</div>

<div class="container d-flex flex-row justify-content-center">
    {% for character in list %}
    <div class="card mx-2" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">{{ character.getName }}</h5>
            <p class="card-text">Level: 0</p>
            <a href="{% url 'character:detail' character.id %}" class="btn btn-sm btn-dark">Pokaż</a>
            <a href="{% url 'character:detail' character.id %}" class="btn btn-sm btn-light">Edytuj</a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

character/templates/party/index.html
{% extends "base.html" %}

{% block title %}Party{% endblock %}

{% block content %}
<div class="px-4 py-5 my-5 text-center">
    <h1 class="display-5 fw-bold text-body-emphasis">Lista postaci</h1>
    <a href="{% url 'character:create' %}}" class="btn btn-sm btn-dark">Dodaj postać</a>
</div>

<div class="container d-flex flex-row justify-content-center">
    {% for character in list %}
    <div class="card mx-2" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">{{ character.getName }}</h5>
            <p class="card-text">Level: {{ character.getLevel }}</p>
            <a href="{% url 'character:detail' character.id %}" class="btn btn-sm btn-dark">Wybierz Quest</a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

character/templates/quest/index.html
{% extends "base.html" %}

{% block title %}Quest List{% endblock %}

{% block content %}
<div class="px-4 py-5 my-5 text-center">
    <h1 class="display-5 fw-bold text-body-emphasis">Wybierz quest</h1>
    <p>{{ character.getName }}</p>
    <p>{{ character.getLevel }}</p>
    <p>{{ character.exp }}</p>
</div>

<table class="table table-dark table-striped">
    {% for quest in quest.getByLevel(Character.getLevel) %}
    <tr>
        <td>{{ quest.name }}</td>
        <td>{{ quest.level }}</td>
        <td>{{ quest.exp }}</td>
        <td>{{ quest.time }}</td>
        <td>
            {% if character.getLevel > quest.level %}
            <a href="#" class="btn btn-small btn-dark">Zacznij</a>
            {% else %}
            <a href="#" class="btn btn-small btn-dark disabled" disabled>Zacznij</a>
            {% endif %}
        </td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

templates/NewCharacterAdd.html
from django import forms
from .models import Character

class CharacterForm(forms.ModelForm):
    class Meta:
        model = Character
        fields = ['name', 'race', 'character_class', 'level']

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>

{% block content %}{% endblock %}

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
</body>
</html>

templates/create_character.html
{% extends "base.html" %}
{% block content %}
  <h2>Create a New Character</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create Character</button>
  </form>
{% endblock %}

user/templates/user/login.html
{% extends "base.html" %}

{% block title %}Zaloguj{% endblock %}

{% block content %}
<div class="container d-flex justify-content-center">
    <main class="w-25 text-center" style="margin-top: 10rem">
        <form action="{% url 'user:login' %}" method="POST">
            {% csrf_token %}
            <h1 class="h3 mb-3 fw-normal">Zaloguj się</h1>
            <div class="form-floating mb-2">
                <input id="floatingInput" name="username" type="text" class="form-control" placeholder="Użytkownik">
                <label for="floatingInput">Nazwa użytkownika</label>
            </div>
            <div class="form-floating mb-2">
                <input id="floatingPassword" name="password" type="password" class="form-control" placeholder="Hasło">
                <label for="floatingPassword">Password</label>
            </div>
            {% if error_message %}
            <div class="alert alert-danger" role="alert">
                {{ error_message }}
            </div>
            {% endif %}
            <button class="btn btn-dark w-100 py-2" type="submit">Zaloguj</button>
            <p class="mt-3">Nie masz konta? <a href="{% url 'user:register' %}" class="btn-dark">Zarejestruj się</a></p>
        </form>
    </main>
</div>
{% endblock %}

user/templates/user/logout.html
{% extends "base.html" %}

{% block title %}Wylogowano pomyślnie{% endblock %}

{% block content %}
<div class="container d-flex justify-content-center">
    <main class="w-25 text-center" style="margin-top: 10rem">
        <h1 class="h3 mb-3 fw-normal">Wylogowano pomyślnie</h1>
        <a href="{% url 'user:login' %}" class="btn-dark">Zaloguj się</a></p>
    </main>
</div>
{% endblock %}

user/templates/user/register.html
{% extends "base.html" %}

{% block title %}Zarejestruj konto{% endblock %}

{% block content %}
<div class="container d-flex justify-content-center">
    <main class="w-25 text-center" style="margin-top: 10rem">
        <form action="{% url 'user:register' %}" method="POST">
            {% csrf_token %}
            <h1 class="h3 mb-3 fw-normal">Zarejestruj konto</h1>
            <div class="form-floating mb-2">
                <input id="floatingInput" name="username" type="text" class="form-control" placeholder="Użytkownik">
                <label for="floatingInput">Nazwa użytkownika</label>
            </div>
            <div class="form-floating mb-2">
                <input id="floatingPassword" name="password" type="password" class="form-control" placeholder="Hasło">
                <label for="floatingPassword">Hasło</label>
            </div>
            <div class="form-floating mb-2">
                <input id="floatingRepeatPassword" name="passwordRepeat" type="password" class="form-control" placeholder="Powtórz hasło">
                <label for="floatingRepeatPassword">Powtórz hasło</label>
            </div>
            {% if error_message %}
            <div class="alert alert-danger" role="alert">
                {{ error_message }}
            </div>
            {% endif %}
            <button class="btn btn-dark w-100 py-2" type="submit">Zarejestruj się</button>
            <p class="mt-3">Masz już konto? <a href="{% url 'user:login' %}" class="btn-dark">Zaloguj się</a></p>
        </form>
    </main>
</div>
{% endblock %}